/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package betterreads;

import java.util.ArrayList;

/**
 *
 * @author Jaden Wickens
 */
public class TeacherControlScreen extends javax.swing.JFrame {

    ArrayList<Review> reviews;
    int numTotReviews;
    UserReviews main = new UserReviews();

    /**
     * Creates new form TeacherControlScreen
     */
    public TeacherControlScreen() {
        //fill relevant variables and call all relevant methods
        reviews = main.getAllReviews();
        numTotReviews = reviews.size();
        System.out.println(reviews.size());
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherInstructionLabel = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reviewDisplay = new javax.swing.JTextArea();
        reviewSelector = new javax.swing.JComboBox<>();
        deleteConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        teacherInstructionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherInstructionLabel.setText("Select review from dropdown menu, then confirm deletion");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        reviewDisplay.setColumns(20);
        reviewDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reviewDisplay.setRows(5);
        reviewDisplay.setText(allReviewsText());
        reviewDisplay.setFocusable(false);
        jScrollPane2.setViewportView(reviewDisplay);

        reviewSelector.setModel(menuLength());
        reviewSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewSelectorActionPerformed(evt);
            }
        });

        deleteConfirm.setText("Delete");
        deleteConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addGap(86, 86, 86)
                .addComponent(reviewSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(teacherInstructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(deleteConfirm)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(reviewSelector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteConfirm)
                    .addComponent(teacherInstructionLabel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed
    /**
     * Handles the action when the delete confirmation button is clicked.
     * Deletes the selected review and updates the user interface accordingly.
     * - Jaden
     *
     * @param evt The ActionEvent triggered when the button is clicked.
     */
    private void deleteConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConfirmActionPerformed
        try {
            //Find which review was selected to be deleted
            int removedReview = Integer.parseInt(reviewSelector.getSelectedItem().toString());
            // delete that review
            main.deleteReview(removedReview);
            //open a new screen that wont contain that review
            TeacherControlScreen t = new TeacherControlScreen();
            t.setVisible(true);
            this.dispose();
        } //Make sure the user selects a review and not the item that says "Make selection"
        catch (NumberFormatException e) {
            teacherInstructionLabel.setText("Please select valid review");
        }
    }//GEN-LAST:event_deleteConfirmActionPerformed

    private void reviewSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewSelectorActionPerformed

    /**
     * Generates a ComboBoxModel with the contents based on the total number of
     * reviews.
     * - Jaden
     *
     * @return A ComboBoxModel containing review length options from 1 to
     * numTotReviews, with the first item as a default "Make Selection:" prompt.
     */
    private javax.swing.ComboBoxModel menuLength() {
        // Create an array to hold the review length options, initialized with size numTotReviews + 1
        String[] numbers = new String[numTotReviews + 1];
        // Set the first element of the array as a default prompt
        numbers[0] = "Make Selection:";
        // Populate the array with review length options from 1 to numTotReviews
        for (int i = 1; i <= numTotReviews; i++) {
            numbers[i] = String.valueOf(i);
        }
        // Create a new DefaultComboBoxModel using the numbers array and return it as a ComboBoxModel
        javax.swing.ComboBoxModel list = new javax.swing.DefaultComboBoxModel<>(numbers);
        return list;
    }

    /**
     * Generates a formatted text containing all reviews stored in the 'reviews'
     * list. Each review is numbered sequentially with user information and
     * ratings.
     * - Jaden
     * 
     * @return A String containing formatted text listing all reviews, including
     * user names and ratings.
     */
    private String allReviewsText() {
        // StringBuilder to build the formatted text
        StringBuilder temp = new StringBuilder();
        // Counter for numbering reviews
        int count = 1;
        // Iterate through each Review object in the 'reviews' list
        for (Review x : reviews) {
            // Extract user name and review rating from the Review object
            String user = x.getUser();
            String review = x.getReview();

            // Append formatted review information to the StringBuilder
            temp.append(count + ". User: " + user + "  Rating: " + review + "\n\n");

            // Increment review count
            count++;
        }
        // Convert StringBuilder to String and return
        return temp.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherControlScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherControlScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherControlScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherControlScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherControlScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton deleteConfirm;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea reviewDisplay;
    private javax.swing.JComboBox<String> reviewSelector;
    private javax.swing.JLabel teacherInstructionLabel;
    // End of variables declaration//GEN-END:variables
}
