/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package betterreads;

import java.util.ArrayList;

/**
 *
 * @author menot
 */
public class TeacherControlScreen extends javax.swing.JFrame {

    ArrayList<Review> reviews;
//    ArrayList<Review> reviews = new ArrayList<>();
    int numTotReviews;
    UserReviews uReviews = new UserReviews();

    /**
     * Creates new form TeacherControlScreen
     */
    public TeacherControlScreen() {
//        reviews.add(new Review("user1", "I liked this book", "5"));
//        reviews.add(new Review("user2", "It was an okay read", "3"));
//        reviews.add(new Review("user3", "Did not enjoy it", "1"));
        reviews = uReviews.getAllReviews();
        numTotReviews = reviews.size();
        System.out.println(reviews.size());
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherInstructionLabel = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reviewDisplay = new javax.swing.JTextArea();
        reviewSelector = new javax.swing.JComboBox<>();
        deleteConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        teacherInstructionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        teacherInstructionLabel.setText("Select review from dropdown menu, then confirm deletion");

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        reviewDisplay.setColumns(20);
        reviewDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reviewDisplay.setRows(5);
        reviewDisplay.setText(allReviewsText());
        reviewDisplay.setFocusable(false);
        jScrollPane2.setViewportView(reviewDisplay);

        reviewSelector.setModel(menuLength());
        reviewSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewSelectorActionPerformed(evt);
            }
        });

        deleteConfirm.setText("Delete");
        deleteConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reviewSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(teacherInstructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(deleteConfirm)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(reviewSelector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteConfirm)
                    .addComponent(teacherInstructionLabel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void deleteConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConfirmActionPerformed
        try {
            int removedReview = Integer.parseInt(reviewSelector.getSelectedItem().toString());
            uReviews.deleteReview(removedReview);
            TeacherControlScreen t = new TeacherControlScreen();
            t.setVisible(true);
            this.dispose();
        } catch (NumberFormatException e) {
            teacherInstructionLabel.setText("Please select valid review");
        }
    }//GEN-LAST:event_deleteConfirmActionPerformed

    private void reviewSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reviewSelectorActionPerformed

    private javax.swing.ComboBoxModel menuLength() {
        String[] numbers = new String[numTotReviews + 1];
        numbers[0] = "Make Selection:";
        for (int i = 1; i <= numTotReviews; i++) {
            numbers[i] = String.valueOf(i);
        }
        javax.swing.ComboBoxModel list = new javax.swing.DefaultComboBoxModel<>(numbers);
        return list;
    }
    
    private String allReviewsText(){
        String allReviews;
        StringBuilder temp = new StringBuilder();
        int count = 1;
        for (Review x:reviews){
            String user = x.getUser();
            String review = x.getReview();
            temp.append(count + ". User: " + user + "  Rating: "+ review+"\n\n");
            count++;
        }
        allReviews = temp.toString();
        
        return allReviews;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherControlScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherControlScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherControlScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherControlScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherControlScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton deleteConfirm;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea reviewDisplay;
    private javax.swing.JComboBox<String> reviewSelector;
    private javax.swing.JLabel teacherInstructionLabel;
    // End of variables declaration//GEN-END:variables
}
